# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffbfeffc21c7815d3a44847dc0a4d8860828bab56fb0a0ef9c31a265beefd7b48727d92bcc76b85d40ae6ffb03410e0715ad20d18adda51a2877dae8a1a084a7

test:
  secret_key_base: d65c51ed398319ddd654d154690fa2b199bf5940d7b26f8f9fa9dd43e16e85383cb3ab91a6168aa7c61dbd1d593612aff078a550a539fa0d4ca6dcee642b445c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
